### ISSUE TITLE
Exception after opening a tab (JTabbedPane) - "java.lang.ArrayIndexOutOfBoundsException" 

### ISSUE THREAD

**Issue by mnemotron** [pago/pgslookandfeel#3]
Hi,

I use your look and feel library in my project Roots.

I get an exception (see below) if I use the JTabbedPane component.
The exception occurs after opening a tab.

Please have a look.
Thanx. Best Regards. mnemotron

Stacktrace:
> Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pagosoft.plaf.PgsTabbedPaneUI.myTabForCoordinate(PgsTabbedPaneUI.java:161)
	at com.pagosoft.plaf.PgsTabbedPaneUI.mySetRolloverTab(PgsTabbedPaneUI.java:154)
	at com.pagosoft.plaf.PgsTabbedPaneUI.access$000(PgsTabbedPaneUI.java:32)
	at com.pagosoft.plaf.PgsTabbedPaneUI$TabRolloverHandler.mouseEntered(PgsTabbedPaneUI.java:457)
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:300)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4676)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4654)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4505)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pago** [comment]
Please let me know if that solves your problem. Thank you for reporting!
